### ISSUE TITLE
Strange behavior in Android

### ISSUE THREAD

**Issue by rodrigodiasf1984** [WrathChaos/react-native-tooltip-2#1]
package version:  "react-native-tooltip-2": "^0.1.3",
react-native version:   "react-native": "0.70.6",

Hi, first i'd like to thank you for this package! 

I'm facing a strage behavior in Android, please take a look at the attached image. 
![image](https://github.com/WrathChaos/react-native-tooltip-2/assets/30758309/8cb4891b-2a47-4f26-bfc3-41b069f1238c)

![image](https://github.com/WrathChaos/react-native-tooltip-2/assets/30758309/cc576be9-1384-4c4a-9209-ea095e4ca2c0)

For some reason the icon or the message shows as duplicated in Android, how can I fix this? 

Thanks

**Comment by rodrigodiasf1984** [comment]
@WrathChaos any idea how to solve it?

**Comment by yagiz2000** [comment]
@rodrigodiasf1984  you need to adjust manually top positioning for android only. It fits perfeclty for my project
```jsx
import { Dimensions, StatusBar } from "react-native";

  <Tooltip
        topAdjustment={Platform.OS === "android" ? -StatusBar.currentHeight : 0}
```

**Comment by rodrigodiasf1984** [comment]
> @rodrigodiasf1984 you need to adjust manually top positioning for android only. It fits perfeclty for my project
> 
> ```js
> import { Dimensions, StatusBar } from "react-native";
> 
>   <Tooltip
>         topAdjustment={Platform.OS === "android" ? -StatusBar.currentHeight : 0}
> ```

Thanks for your reply, i've moved to another package, i couldn't wait, the issue is open on december of 2023, i understand, feel free to close the issue @WrathChaos

**Comment by AboodyAlaze** [comment]
@WrathChaos 
Can You Please What The Name Of Package that you Move for it because there is no package

**Comment by kuraydev** [comment]
react-native-tooltip-2 is still available, he just using another package. @AboodyAlaze

**Comment by rodrigodiasf1984** [comment]
> @AboodyAlaze Can You Please What The Name Of Package that you Move for it because there is no package

im using rn-tooltip
